# Generated by Django 3.2.7 on 2021-10-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlog', '0003_alter_groups_cjoin'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='tf',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groups',
            name='cjoin',
            field=models.IntegerField(default=0),
        ),
    ]
