# Generated by Django 3.2.7 on 2021-10-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlog', '0005_auto_20211030_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='cpost',
            field=models.IntegerField(default=0),
        ),
    ]
