# Generated by Django 3.2.7 on 2021-10-30 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlog', '0006_groups_cpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_by',
            field=models.CharField(default=',', max_length=100),
        ),
    ]
