# Generated by Django 3.2.7 on 2021-10-31 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signlog', '0007_post_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-dt',)},
        ),
        migrations.AddField(
            model_name='groups',
            name='usrname',
            field=models.CharField(default=',', max_length=256),
        ),
        migrations.AddField(
            model_name='groups',
            name='usrrname',
            field=models.CharField(default=',', max_length=256),
        ),
        migrations.AddField(
            model_name='post',
            name='dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
